FROM mongo:latest
# Copia os ficheiros para dentro da imagem durante o build
COPY dataset_jogos_tratado.json /docker-entrypoint-initdb.d/
COPY dataset_autores_tratado.json /docker-entrypoint-initdb.d/
COPY dataset_categorias_tratado.json /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/
